/**
 * @description Lista de 195 países con ISO alpha-2, ISO alpha-3 y nombre en ES/EN.
 * Ordenados por volumen comercial global primero, luego alfabético por nombre en español.
 * Usado por:
 *   - GET /api/classifier/countries — endpoint del frontend para poblar CountrySelector
 *   - tariff.service.js — validación de ISO alpha-3 antes de consultar fuentes
 *   - CountrySelector.jsx — convierte ISO-2 (bandera UI) a ISO-3 (backend) antes del submit
 */
const countries = [
  // ── Mayores economías comerciales (orden por volumen de comercio global) ─────
  { iso2: 'CN', iso3: 'CHN', es: 'China',                  en: 'China'                  },
  { iso2: 'US', iso3: 'USA', es: 'Estados Unidos',         en: 'United States'          },
  { iso2: 'DE', iso3: 'DEU', es: 'Alemania',               en: 'Germany'                },
  { iso2: 'JP', iso3: 'JPN', es: 'Japón',                  en: 'Japan'                  },
  { iso2: 'NL', iso3: 'NLD', es: 'Países Bajos',           en: 'Netherlands'            },
  { iso2: 'GB', iso3: 'GBR', es: 'Reino Unido',            en: 'United Kingdom'         },
  { iso2: 'KR', iso3: 'KOR', es: 'Corea del Sur',          en: 'South Korea'            },
  { iso2: 'FR', iso3: 'FRA', es: 'Francia',                en: 'France'                 },
  { iso2: 'HK', iso3: 'HKG', es: 'Hong Kong',              en: 'Hong Kong'              },
  { iso2: 'IT', iso3: 'ITA', es: 'Italia',                 en: 'Italy'                  },
  { iso2: 'CA', iso3: 'CAN', es: 'Canadá',                 en: 'Canada'                 },
  { iso2: 'BE', iso3: 'BEL', es: 'Bélgica',               en: 'Belgium'                },
  { iso2: 'MX', iso3: 'MEX', es: 'México',                 en: 'Mexico'                 },
  { iso2: 'SG', iso3: 'SGP', es: 'Singapur',               en: 'Singapore'              },
  { iso2: 'IN', iso3: 'IND', es: 'India',                  en: 'India'                  },
  { iso2: 'RU', iso3: 'RUS', es: 'Rusia',                  en: 'Russia'                 },
  { iso2: 'AU', iso3: 'AUS', es: 'Australia',              en: 'Australia'              },
  { iso2: 'ES', iso3: 'ESP', es: 'España',                 en: 'Spain'                  },
  { iso2: 'CH', iso3: 'CHE', es: 'Suiza',                  en: 'Switzerland'            },
  { iso2: 'PL', iso3: 'POL', es: 'Polonia',                en: 'Poland'                 },
  { iso2: 'SE', iso3: 'SWE', es: 'Suecia',                 en: 'Sweden'                 },
  { iso2: 'TH', iso3: 'THA', es: 'Tailandia',              en: 'Thailand'               },
  { iso2: 'BR', iso3: 'BRA', es: 'Brasil',                 en: 'Brazil'                 },
  { iso2: 'AE', iso3: 'ARE', es: 'Emiratos Árabes Unidos', en: 'United Arab Emirates'   },
  { iso2: 'MY', iso3: 'MYS', es: 'Malasia',                en: 'Malaysia'               },
  { iso2: 'VN', iso3: 'VNM', es: 'Vietnam',                en: 'Vietnam'                },
  { iso2: 'ID', iso3: 'IDN', es: 'Indonesia',              en: 'Indonesia'              },
  { iso2: 'TR', iso3: 'TUR', es: 'Turquía',                en: 'Turkey'                 },
  { iso2: 'SA', iso3: 'SAU', es: 'Arabia Saudita',         en: 'Saudi Arabia'           },
  { iso2: 'CZ', iso3: 'CZE', es: 'República Checa',        en: 'Czech Republic'         },
  { iso2: 'ZA', iso3: 'ZAF', es: 'Sudáfrica',              en: 'South Africa'           },
  { iso2: 'AT', iso3: 'AUT', es: 'Austria',                en: 'Austria'                },
  { iso2: 'DK', iso3: 'DNK', es: 'Dinamarca',              en: 'Denmark'                },
  { iso2: 'NO', iso3: 'NOR', es: 'Noruega',                en: 'Norway'                 },
  { iso2: 'PH', iso3: 'PHL', es: 'Filipinas',              en: 'Philippines'            },
  { iso2: 'FI', iso3: 'FIN', es: 'Finlandia',              en: 'Finland'                },
  { iso2: 'HU', iso3: 'HUN', es: 'Hungría',                en: 'Hungary'                },
  { iso2: 'IL', iso3: 'ISR', es: 'Israel',                 en: 'Israel'                 },
  { iso2: 'NZ', iso3: 'NZL', es: 'Nueva Zelanda',          en: 'New Zealand'            },
  { iso2: 'RO', iso3: 'ROU', es: 'Rumanía',                en: 'Romania'                },
  { iso2: 'PT', iso3: 'PRT', es: 'Portugal',               en: 'Portugal'               },
  { iso2: 'EG', iso3: 'EGY', es: 'Egipto',                 en: 'Egypt'                  },
  { iso2: 'IR', iso3: 'IRN', es: 'Irán',                   en: 'Iran'                   },
  { iso2: 'IQ', iso3: 'IRQ', es: 'Iraq',                   en: 'Iraq'                   },
  { iso2: 'KW', iso3: 'KWT', es: 'Kuwait',                 en: 'Kuwait'                 },
  { iso2: 'QA', iso3: 'QAT', es: 'Catar',                  en: 'Qatar'                  },
  { iso2: 'NG', iso3: 'NGA', es: 'Nigeria',                en: 'Nigeria'                },
  { iso2: 'SK', iso3: 'SVK', es: 'Eslovaquia',             en: 'Slovakia'               },
  { iso2: 'GR', iso3: 'GRC', es: 'Grecia',                 en: 'Greece'                 },
  { iso2: 'CL', iso3: 'CHL', es: 'Chile',                  en: 'Chile'                  },
  { iso2: 'CO', iso3: 'COL', es: 'Colombia',               en: 'Colombia'               },
  { iso2: 'AR', iso3: 'ARG', es: 'Argentina',              en: 'Argentina'              },
  { iso2: 'PE', iso3: 'PER', es: 'Perú',                   en: 'Peru'                   },
  { iso2: 'EC', iso3: 'ECU', es: 'Ecuador',                en: 'Ecuador'                },
  { iso2: 'BO', iso3: 'BOL', es: 'Bolivia',                en: 'Bolivia'                },
  { iso2: 'PY', iso3: 'PRY', es: 'Paraguay',               en: 'Paraguay'               },
  { iso2: 'UY', iso3: 'URY', es: 'Uruguay',                en: 'Uruguay'                },
  { iso2: 'VE', iso3: 'VEN', es: 'Venezuela',              en: 'Venezuela'              },
  { iso2: 'PA', iso3: 'PAN', es: 'Panamá',                 en: 'Panama'                 },
  { iso2: 'CR', iso3: 'CRI', es: 'Costa Rica',             en: 'Costa Rica'             },
  { iso2: 'GT', iso3: 'GTM', es: 'Guatemala',              en: 'Guatemala'              },
  { iso2: 'HN', iso3: 'HND', es: 'Honduras',               en: 'Honduras'               },
  { iso2: 'SV', iso3: 'SLV', es: 'El Salvador',            en: 'El Salvador'            },
  { iso2: 'NI', iso3: 'NIC', es: 'Nicaragua',              en: 'Nicaragua'              },
  { iso2: 'DO', iso3: 'DOM', es: 'República Dominicana',   en: 'Dominican Republic'     },
  { iso2: 'CU', iso3: 'CUB', es: 'Cuba',                   en: 'Cuba'                   },
  { iso2: 'JM', iso3: 'JAM', es: 'Jamaica',                en: 'Jamaica'                },
  { iso2: 'TT', iso3: 'TTO', es: 'Trinidad y Tobago',      en: 'Trinidad and Tobago'    },
  { iso2: 'MA', iso3: 'MAR', es: 'Marruecos',              en: 'Morocco'                },
  { iso2: 'DZ', iso3: 'DZA', es: 'Argelia',                en: 'Algeria'                },
  { iso2: 'TN', iso3: 'TUN', es: 'Túnez',                  en: 'Tunisia'                },
  { iso2: 'GH', iso3: 'GHA', es: 'Ghana',                  en: 'Ghana'                  },
  { iso2: 'KE', iso3: 'KEN', es: 'Kenia',                  en: 'Kenya'                  },
  { iso2: 'ET', iso3: 'ETH', es: 'Etiopía',                en: 'Ethiopia'               },
  { iso2: 'TZ', iso3: 'TZA', es: 'Tanzania',               en: 'Tanzania'               },
  { iso2: 'UG', iso3: 'UGA', es: 'Uganda',                 en: 'Uganda'                 },
  { iso2: 'AO', iso3: 'AGO', es: 'Angola',                 en: 'Angola'                 },
  { iso2: 'CM', iso3: 'CMR', es: 'Camerún',                en: 'Cameroon'               },
  { iso2: 'CI', iso3: 'CIV', es: 'Costa de Marfil',        en: 'Ivory Coast'            },
  { iso2: 'BD', iso3: 'BGD', es: 'Bangladés',              en: 'Bangladesh'             },
  { iso2: 'PK', iso3: 'PAK', es: 'Pakistán',               en: 'Pakistan'               },
  { iso2: 'LK', iso3: 'LKA', es: 'Sri Lanka',              en: 'Sri Lanka'              },
  { iso2: 'MM', iso3: 'MMR', es: 'Myanmar',                en: 'Myanmar'                },
  { iso2: 'KH', iso3: 'KHM', es: 'Camboya',                en: 'Cambodia'               },
  { iso2: 'UA', iso3: 'UKR', es: 'Ucrania',                en: 'Ukraine'                },
  { iso2: 'BY', iso3: 'BLR', es: 'Bielorrusia',            en: 'Belarus'                },
  { iso2: 'KZ', iso3: 'KAZ', es: 'Kazajistán',             en: 'Kazakhstan'             },
  { iso2: 'UZ', iso3: 'UZB', es: 'Uzbekistán',             en: 'Uzbekistan'             },
  { iso2: 'GE', iso3: 'GEO', es: 'Georgia',                en: 'Georgia'                },
  { iso2: 'AM', iso3: 'ARM', es: 'Armenia',                en: 'Armenia'                },
  { iso2: 'AZ', iso3: 'AZE', es: 'Azerbaiyán',             en: 'Azerbaijan'             },
  { iso2: 'IE', iso3: 'IRL', es: 'Irlanda',                en: 'Ireland'                },
  { iso2: 'LU', iso3: 'LUX', es: 'Luxemburgo',             en: 'Luxembourg'             },
  { iso2: 'HR', iso3: 'HRV', es: 'Croacia',                en: 'Croatia'                },
  { iso2: 'BG', iso3: 'BGR', es: 'Bulgaria',               en: 'Bulgaria'               },
  { iso2: 'RS', iso3: 'SRB', es: 'Serbia',                 en: 'Serbia'                 },
  { iso2: 'SI', iso3: 'SVN', es: 'Eslovenia',              en: 'Slovenia'               },
  { iso2: 'LT', iso3: 'LTU', es: 'Lituania',               en: 'Lithuania'              },
  { iso2: 'LV', iso3: 'LVA', es: 'Letonia',                en: 'Latvia'                 },
  { iso2: 'EE', iso3: 'EST', es: 'Estonia',                en: 'Estonia'                },
  { iso2: 'IS', iso3: 'ISL', es: 'Islandia',               en: 'Iceland'                },
  { iso2: 'OM', iso3: 'OMN', es: 'Omán',                   en: 'Oman'                   },
  { iso2: 'JO', iso3: 'JOR', es: 'Jordania',               en: 'Jordan'                 },
  { iso2: 'LB', iso3: 'LBN', es: 'Líbano',                 en: 'Lebanon'                },
  { iso2: 'SY', iso3: 'SYR', es: 'Siria',                  en: 'Syria'                  },
  { iso2: 'BH', iso3: 'BHR', es: 'Baréin',                 en: 'Bahrain'                },
  { iso2: 'YE', iso3: 'YEM', es: 'Yemen',                  en: 'Yemen'                  },
  { iso2: 'NP', iso3: 'NPL', es: 'Nepal',                  en: 'Nepal'                  },
  { iso2: 'MN', iso3: 'MNG', es: 'Mongolia',               en: 'Mongolia'               },
  { iso2: 'TW', iso3: 'TWN', es: 'Taiwán',                 en: 'Taiwan'                 },
  { iso2: 'MO', iso3: 'MAC', es: 'Macao',                  en: 'Macao'                  },
  { iso2: 'SN', iso3: 'SEN', es: 'Senegal',                en: 'Senegal'                },
  { iso2: 'SD', iso3: 'SDN', es: 'Sudán',                  en: 'Sudan'                  },
  { iso2: 'ZM', iso3: 'ZMB', es: 'Zambia',                 en: 'Zambia'                 },
  { iso2: 'ZW', iso3: 'ZWE', es: 'Zimbabue',               en: 'Zimbabwe'               },
  { iso2: 'MZ', iso3: 'MOZ', es: 'Mozambique',             en: 'Mozambique'             },
  { iso2: 'MG', iso3: 'MDG', es: 'Madagascar',             en: 'Madagascar'             },
  { iso2: 'CD', iso3: 'COD', es: 'Congo (RDC)',            en: 'DR Congo'               },
  { iso2: 'CG', iso3: 'COG', es: 'Congo (Rep.)',           en: 'Republic of Congo'      },
  { iso2: 'RW', iso3: 'RWA', es: 'Ruanda',                 en: 'Rwanda'                 },
  { iso2: 'LY', iso3: 'LBY', es: 'Libia',                  en: 'Libya'                  },
  { iso2: 'GA', iso3: 'GAB', es: 'Gabón',                  en: 'Gabon'                  },
  { iso2: 'MU', iso3: 'MUS', es: 'Mauricio',               en: 'Mauritius'              },
  { iso2: 'CV', iso3: 'CPV', es: 'Cabo Verde',             en: 'Cape Verde'             },
  { iso2: 'FJ', iso3: 'FJI', es: 'Fiyi',                   en: 'Fiji'                   },
  { iso2: 'PG', iso3: 'PNG', es: 'Papúa Nueva Guinea',     en: 'Papua New Guinea'       },
  { iso2: 'AF', iso3: 'AFG', es: 'Afganistán',             en: 'Afghanistan'            },
  { iso2: 'AL', iso3: 'ALB', es: 'Albania',                en: 'Albania'                },
  { iso2: 'BA', iso3: 'BIH', es: 'Bosnia y Herzegovina',   en: 'Bosnia and Herzegovina' },
  { iso2: 'MK', iso3: 'MKD', es: 'Macedonia del Norte',    en: 'North Macedonia'        },
  { iso2: 'ME', iso3: 'MNE', es: 'Montenegro',             en: 'Montenegro'             },
  { iso2: 'XK', iso3: 'XKX', es: 'Kosovo',                 en: 'Kosovo'                 },
  { iso2: 'MD', iso3: 'MDA', es: 'Moldavia',               en: 'Moldova'                },
  { iso2: 'MX', iso3: 'MEX', es: 'México',                 en: 'Mexico'                 },
  { iso2: 'BS', iso3: 'BHS', es: 'Bahamas',                en: 'Bahamas'                },
  { iso2: 'BB', iso3: 'BRB', es: 'Barbados',               en: 'Barbados'               },
  { iso2: 'GY', iso3: 'GUY', es: 'Guyana',                 en: 'Guyana'                 },
  { iso2: 'SR', iso3: 'SUR', es: 'Surinam',                en: 'Suriname'               },
  { iso2: 'BZ', iso3: 'BLZ', es: 'Belice',                 en: 'Belize'                 },
  { iso2: 'HT', iso3: 'HTI', es: 'Haití',                  en: 'Haiti'                  },
];

// Eliminar duplicados por iso3 manteniendo el primero
const seen = new Set();
const uniqueCountries = countries.filter((c) => {
  if (seen.has(c.iso3)) return false;
  seen.add(c.iso3);
  return true;
});

/**
 * @description Mapa iso3 → country para lookups rápidos en el backend.
 */
const iso3Map = Object.fromEntries(uniqueCountries.map((c) => [c.iso3, c]));

/**
 * @description Mapa iso2 → iso3 para conversión en CountrySelector.jsx antes del submit.
 */
const iso2ToIso3 = Object.fromEntries(uniqueCountries.map((c) => [c.iso2, c.iso3]));

module.exports = { countries: uniqueCountries, iso3Map, iso2ToIso3 };
